name: SeichiAssist
main: com.github.unchama.seichiassist.SeichiAssist
version: 0.8.7

commands:
  gacha:
      description: This is a gacha command.
      usage: /<command> <help>
      permission: multiseichiplugin.seichi
      permission-message: You don't have <permission>
  seichi:
      description: This is a seichi command.
      usage: /<command> <help>
      permission: multiseichiplugin.seichi
      permission-message: You don't have <permission>
  ef:
      description: This is a Effect toggle command.
      usage: /<command> <smart/demo>
      permission: multiseichiplugin.ef
      permission-message: You don't have <permission>
  level:
      description: This is a level command.
      usage: /<command> <reset>
      permission: multiseichiplugin.level
      permission-message: You don't have <permission>
  lastquit:
      description: This is a lastquit command.
      usage: /<command> <playername>
      permission: multiseichiplugin.lastquit
      permission-message: You don't have <permission>